version: "3.8"
services:
  backend:
    image: "mu86/springboot-react-fullstack:31.8.2021.13.38.40"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev